# Generated by Django 3.1.4 on 2020-12-25 14:44

from django.db import migrations
import requests


def update_table(apps, schema_editor):
    users_get = requests.get('http://jsonplaceholder.typicode.com/users')
    users = users_get.json()
    posts_get = requests.get('http://jsonplaceholder.typicode.com/posts')
    posts = posts_get.json()

    id_users = []
    name_users = []

    users_ID = []
    posts_themes = []
    posts_texts = []

    for data in users:
        id_users.append(data['id'])
        name_users.append(data['name'])

    for data in posts:
        users_ID.append(data['userId'])
        posts_themes.append(data['title'])
        posts_texts.append(data['body'])

    User = apps.get_model('table', 'User')
    Post = apps.get_model('table', 'Post')

    for id, name in zip(id_users, name_users):
        data = User(user_id=id, user_name=name)
        data.save()

    for id, theme, text in zip(users_ID, posts_themes, posts_texts):
        post = Post(user_id=id, post_theme=theme, post_text=text)
        post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_table)
    ]
